import assert from 'node:assert/strict';
import {deduplicateEventsTwoContour} from '../../src/features/events/eventDuplicateResolution.js';
const E=[];
E.push({title:'TATTOOMO 2026',eventDate:'2026-08-21',displayDate:'21.08.26–23.08.26',timeLabel:'10:00–21:30',venue:'МТС Live Hall',participants:'НРРТР',description:'Тату-фестиваль с мастер-классами.',_compactTimeSource:'21.08.26–23.08.26 10:00–21:30',sourceType:'telegram',sourceName:'@kurazhcity',sourceUrl:'tg1'});
E.push({title:'TATTOOMO 2026 — тату-фестиваль с мастер-классами и показом работ мастеров',eventDate:'2026-08-21',displayDate:'21.08.26–23.08.26',timeLabel:'21:08',venue:'МТС Live Hall',participants:'НРРТР',description:'Мастер-классы и музыкальная часть.',_compactTimeSource:'21.08.26–23.08.26',sourceType:'vk',sourceName:'Беседа 22'});
E.push({title:'Мото Што-то!',eventDate:'2026-08-21',displayDate:'21.08.26–22.08.26',timeLabel:'17:00; 12:00',venue:'турбаза Астра, Новая Усмань',participants:'Такие Дела, РАДА ВЕЛЕС, Хижина Дядюшки Джо, ЛИАНА, Синергия, Eleanore Begin, Советское Барахло',description:'Двухдневный байкерский фестиваль.',_compactTimeSource:'21.08.26 17:00; 22.08.26 12:00; чужая дата 31.08.26',sourceType:'tg',sourceName:'x',sourceUrl:'m1'});
E.push({...E[2],eventDate:'2026-08-22',sourceType:'vk',sourceName:'y',sourceUrl:'m2',description:'Байкерский фестиваль, баня и маркеты.'});
E.push({title:'Двойной Кураж — концерт с гостями из Липецка и ответом местной сцены',eventDate:'2026-08-21',displayDate:'21 августа 2026',timeLabel:'19:00',venue:'The Last of Vavilone',participants:'ELIJAH GOOD, ТРИПП, Мера Беспорядка',description:'Концерт с гостями из Липецка.',_compactTimeSource:'21.08.26 19:00; чужая дата 31.08.26'});
E.push({title:'Звуки на грани Лета',eventDate:'2026-08-21',displayDate:'21 августа 2026',timeLabel:'20:00',venue:'Мама Анархия',participants:'Screaming Queens, Ne-mo, Без мрака',description:'Локальный концерт трёх молодых команд.'});
E.push({title:'The Second-to-Last Saturday',eventDate:'2026-08-22',displayDate:'22 августа 2026',timeLabel:'19:00',venue:'Diesel Bar',participants:'Без Мрака, Переломный момент, Паническая защита',description:'Вечер с тремя группами.'});
E.push({title:'Котик 22.08.26',eventDate:'2026-08-22',displayDate:'22 августа 2026',timeLabel:'19:30',venue:'DIESEL HALL, Воронеж',participants:'Ночное отделение, Последняя Птчка, LISD',description:'Вечер нишевых проектов.'});
E.push({title:'Мультижанровый фестиваль «Русское лето 2026»',eventDate:'2026-08-29',displayDate:'29 августа 2026',timeLabel:'11:00',venue:'Советская площадь',participants:'',description:'Большой летний фестиваль.'});
const r=await deduplicateEventsTwoContour(E,{arbitrateAmbiguous: async ps=>new Map(ps.map(p=>[p.key,{verdict:'different',confidence:.99,reason:'test'}]))});
assert.equal(r.events.length, 7);
const tattoo=r.events.find((e)=>String(e.title).startsWith('TATTOOMO'));
const moto=r.events.find((e)=>e.title==='Мото Што-то!');
const dieselA=r.events.find((e)=>e.title==='The Second-to-Last Saturday');
const dieselB=r.events.find((e)=>String(e.title).startsWith('Котик'));
assert.ok(tattoo && moto && dieselA && dieselB);
assert.equal(tattoo.eventDays.length,3);
assert.equal(moto.eventDays.length,2);
assert.equal(tattoo.participants,'НРРТР');
assert.doesNotMatch(tattoo.participants,/Такие Дела|РАДА ВЕЛЕС/u);
assert.doesNotMatch(dieselA.participants,/Ночное отделение|LISD/u);
assert.doesNotMatch(dieselB.participants,/Без Мрака|Паническая защита/u);
assert.ok(tattoo.eventDays.every((d)=>d.timeLabel!=='21:08'));
console.log('eventAugustSnapshotV95.test.mjs: OK');
